# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='suite.User')),
                ('preferred_name', models.CharField(blank=True, max_length=20)),
                ('graduation_year', models.IntegerField(blank=True)),
                ('major', models.CharField(blank=True, max_length=20)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('GPA', models.DecimalField(blank=True, decimal_places=3, max_digits=4)),
            ],
        ),
    ]
