# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0002_auto_20170219_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='first_seen',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='club',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
