# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0002_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('club_type', models.CharField(max_length=20)),
                ('club_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=1000)),
                ('event_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessibility', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suite.Club')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='student_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
