# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0003_auto_20170218_0535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='account',
            name='GPA',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='graduation_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='student_title',
            field=models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduate'), ('O', 'Others')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
