# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0006_auto_20170220_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='/static/images/default22.jpg', upload_to='media/'),
        ),
    ]
