# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0008_auto_20170220_0012'),
        ('suite', '0003_auto_20170219_2311'),
    ]

    operations = [
    ]
