# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0009_merge_20170220_0640'),
        ('suite', '0003_auto_20170219_2310'),
    ]

    operations = [
    ]
