# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0010_merge_20170221_0743'),
        ('suite', '0003_auto_20170219_2310'),
    ]

    operations = [
    ]
