# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0011_auto_20170223_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': (('O', 'Owner'), ('A', 'Admin/Officer'), ('M', 'Member'), ('P', 'Passerby'))},
        ),
    ]
