# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0010_merge_20170222_0043'),
        ('suite', '0011_merge_20170221_0803'),
    ]

    operations = [
    ]
