# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0012_auto_20170224_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(choices=[('O', 'Owner'), ('A', 'Officer'), ('M', 'Member'), ('P', 'Passerby'), ('R', 'Requested')], default='P', max_length=1),
        ),
    ]
