# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0013_auto_20170224_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': (('O', 'Owner'), ('A', 'Admin/Officer'), ('M', 'Member'), ('P', 'Passerby'), ('can_view_stats', 'Can view individual member stats'), ('can_create_event', 'Can create an event for this club'), ('can_add_receipt', 'Can add a receipt'), ('can_remove_receipt', 'Can remove a receipt'), ('can_access_attendance', 'Can access member attendance'), ('can_access_budget', 'Can access the budgets for this club'), ('can_create_budget', 'Can create a budget'), ('can_request_reimbusement', 'Can request for a reimbursement'), ('can_handle_reimbursement', 'Can handle reimbursement'))},
        ),
    ]
