# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0013_merge_20170225_0033'),
        ('suite', '0012_merge_20170224_0720'),
    ]

    operations = [
    ]
