# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0014_merge_20170225_2354'),
        ('suite', '0012_merge_20170224_2147'),
    ]

    operations = [
    ]
