# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0014_auto_20170224_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(choices=[('owner', 'Owner'), ('officer', 'Officer'), ('member', 'Member'), ('passerby', 'Passerby'), ('join', 'Join Requested'), ('promote', 'Promotion Requested')], default='passerby', max_length=10),
        ),
    ]
