# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0015_auto_20170224_0158'),
        ('suite', '0011_merge_20170223_2219'),
    ]

    operations = [
    ]
