# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0016_club_members'),
        ('suite', '0012_merge_20170224_0623'),
    ]

    operations = [
    ]
