# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0016_club_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': (('O', 'Owner'), ('A', 'Admin/Officer'), ('M', 'Member'), ('P', 'Passerby'), ('can_view_stats', 'Can view individual member stats'), ('can_create_event', 'Can create an event for this club'), ('can_add_receipt', 'Can add a receipt'), ('can_remove_receipt', 'Can remove a receipt'), ('can_access_attendance', 'Can access member attendance'), ('can_access_budget', 'Can access the budgets for this club'), ('can_create_budget', 'Can create a budget'), ('can_request_reimbusement', 'Can request for a reimbursement'), ('can_handle_reimbursement', 'Can handle reimbursement'))},
        ),
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.RemoveField(
            model_name='role',
            name='title',
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
