# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0017_auto_20170226_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='role',
            name='uid',
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': (('O', 'Owner'), ('A', 'Admin/Officer'), ('M', 'Member'), ('P', 'Passerby'), ('can_handle_join_requests', 'Can handle join requests'), ('can_handle_promotion_requests', 'Can handle promotion requests'), ('can_view_stats', 'Can view individual member stats'), ('can_create_event', 'Can create an event for this club'), ('can_add_receipt', 'Can add a receipt'), ('can_remove_receipt', 'Can remove a receipt'), ('can_access_attendance', 'Can access member attendance'), ('can_access_budget', 'Can access the budgets for this club'), ('can_create_budget', 'Can create a budget'), ('can_request_reimbusement', 'Can request for a reimbursement'), ('can_handle_reimbursement', 'Can handle reimbursement'))},
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
