# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0017_auto_20170226_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='did',
        ),
    ]
