# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0018_remove_event_did'),
        ('suite', '0019_auto_20170227_1207'),
    ]

    operations = [
    ]
