# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0021_auto_20170227_2231'),
        ('suite', '0017_merge_20170226_2345'),
    ]

    operations = [
    ]
