# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0022_auto_20170228_2127'),
        ('suite', '0022_auto_20170301_0407'),
    ]

    operations = [
    ]
