# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0025_auto_20170303_0812'),
        ('suite', '0023_merge_20170303_0137'),
    ]

    operations = [
    ]
