# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0027_auto_20170303_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='static/media/default.jpg', upload_to=''),
        ),
    ]
