# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0027_auto_20170303_1222'),
        ('suite', '0023_merge_20170302_2218'),
    ]

    operations = [
    ]
