# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0028_merge_20170303_2001'),
        ('suite', '0028_merge_20170304_1821'),
    ]

    operations = [
    ]
