# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0028_auto_20170304_2059'),
        ('suite', '0029_remove_budget_used'),
    ]

    operations = [
    ]
