# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0030_merge_20170304_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='static/media/special_event.png', upload_to=''),
        ),
    ]
