# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0031_event_image'),
        ('suite', '0030_merge_20170304_2229'),
    ]

    operations = [
    ]
