# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0032_merge_20170304_2322'),
        ('suite', '0032_merge_20170304_2248'),
    ]

    operations = [
    ]
