# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0029_merge_20170304_1910'),
        ('suite', '0032_merge_20170304_2248'),
    ]

    operations = [
    ]
