# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0033_merge_20170305_0034'),
        ('suite', '0033_merge_20170305_0031'),
    ]

    operations = [
    ]
