# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0034_merge_20170305_0312'),
        ('suite', '0034_merge_20170305_0617'),
    ]

    operations = [
    ]
