# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0035_auto_20170306_0219'),
        ('suite', '0034_merge_20170305_0617'),
    ]

    operations = [
    ]
