# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0036_merge_20170306_0416'),
        ('suite', '0036_merge_20170306_0347'),
    ]

    operations = [
    ]
