# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0037_merge_20170306_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
