# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0038_event_event_fee'),
        ('suite', '0036_merge_20170306_0237'),
    ]

    operations = [
    ]
