# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0039_auto_20170306_1856'),
        ('suite', '0040_auto_20170307_0516'),
    ]

    operations = [
    ]
