# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0041_merge_20170308_0032'),
        ('suite', '0039_auto_20170307_2145'),
    ]

    operations = [
    ]
