# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0042_merge_20170308_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='reason',
            field=models.TextField(),
        ),
    ]
