# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0042_merge_20170308_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default=b'default.jpg', upload_to=b''),
        ),
    ]
