# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 01:36
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0045_auto_20170310_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=stdimage.models.StdImageField(default='static/media/special_event.png', upload_to=''),
        ),
    ]
