# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0046_auto_20170311_0136'),
        ('suite', '0043_auto_20170308_1914'),
    ]

    operations = [
    ]
