# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:15
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0047_merge_20170311_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=stdimage.models.StdImageField(default=b'default.jpg', upload_to=b''),
        ),
    ]
