# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:47
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0048_auto_20170311_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=stdimage.models.StdImageField(default=b'special_event.png', upload_to=b''),
        ),
    ]
